### ISSUE TITLE
Request textDocument/hover failed.

### ISSUE THREAD

**Issue by mortscode** [ArdenIvanov/svelte-intellisense#14]
When working in Sapper with Svelte, this error keeps popping up:

```
Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'helpers' of undefined
  Code: -32603 
```

It seems to be tied to the Svelte Intellisense:
![EditBurger_svelte_—_burgerweek-2_0](https://user-images.githubusercontent.com/3239582/61005011-2a8ff500-a31c-11e9-8e9a-d2a93d89c2ea.jpg)

Anyone else experiencing this issue?

**Comment by PatrickG** [comment]
I get a similar error:
```[Error - 14:33:27] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'events' of undefined
  Code: -32603 ```

**Comment by arxpoetica** [comment]
This started happening and automatically opening my output window, and it's driving me batty. I had to disable the plugin.

**Comment by scottwater** [comment]
Is there any way to disable the "hover" functionality?

**Comment by Highter87** [comment]
> This started happening and automatically opening my output window, and it's driving me batty. I had to disable the plugin.

me too

**Comment by Achudh** [comment]
Hello Supper Sapper Devs it would be awesome if you could  please make this one priority, and do let me know how i could contribute to the code.

**Comment by Achudh** [comment]
Hello Svelte devs it would be awesome if you could please make this one priority, and do let me know how i could contribute to the code.

**Comment by itslearningappsteam** [comment]
I haven't seen this issue myself, do you have any steps to reproduce it - pieces of code which cause this error?

**Comment by ArdenIvanov** [comment]
I haven't seen this issue myself, do you have any steps to reproduce it - pieces of code which cause this error?

**Comment by Highter87** [comment]
> I haven't seen this issue myself, do you have any steps to reproduce it - pieces of code which cause this error?

hover mouse on anything from svelte code

**Comment by ArdenIvanov** [comment]
It gives me proper hover information from the code, no error

**Comment by Achudh** [comment]
The issue was automatically resolved ! After I restarted my server

**Comment by Highter87** [comment]
you can see on video https://dropmefiles.com/z6a4L

**Comment by arxpoetica** [comment]
Thanks for the fix, @ArdenIvanov. How do we know when it's been pushed so we can start using?

**Comment by itslearningappsteam** [comment]
Thanks, the issue is caused by using "{function() {}}" in event handler - parser cannot parse it. 
This kind of errors are supressed in version 0.7.1, but until parser is fixed, no intellisense will be available for components with such handlers.
For now you can use lambda "{() => {} }" and intellisense will work fine.

**Comment by itslearningappsteam** [comment]
Thanks, the issue is caused by using "{function() {}}" in event handler - parser cannot parse it. 
This kind of errors are supressed in version 0.7.1, but until parser is fixed, no intellisense will be available for components with such handlers.
For now you can use lambda "{() => {} }" and intellisense will work fine.

**Comment by ArdenIvanov** [comment]
Thanks, the issue is caused by using "{function() {}}" in event handler - parser cannot parse it.
This kind of errors are supressed in version 0.7.1, but until parser is fixed, no intellisense will be available for components with such handlers.
For now you can use lambda "{() => {} }" and intellisense will work fine.

**Comment by ArdenIvanov** [comment]
Thanks, the issue is caused by using "{function() {}}" in event handler - parser cannot parse it.
This kind of errors are supressed in version 0.7.1, but until parser is fixed, no intellisense will be available for components with such handlers.
For now you can use lambda "{() => {} }" and intellisense will work fine.

**Comment by ArdenIvanov** [comment]
@arxpoetica it is published now, you can update

**Comment by arxpoetica** [comment]
Thanks, I can confirm it's working correctly again.

**Comment by alexprey** [comment]
@ArdenIvanov issue also was fixed from my side https://github.com/alexprey/sveltedoc-parser/releases/tag/2.3.1

**Comment by thebrianbug** [comment]
I'm seeing this error again :(

**Comment by pyronaur** [comment]
Seeing the error as well

**Comment by noopurphalak** [comment]
Seeing the error again....

**Comment by alexruimy** [comment]
Seeing the error as well

**Comment by andreyluiz** [comment]
Not only this error is back, but it also is very annoying, because VS Code pops the Output panel at your face every time this error happens. And it happens whenever you hover the mouse over the code.

**Comment by ogrotten** [comment]
This started happening to me somewhere about a week ago (mid Oct, 2021). I have no idea what started it, I looked over to the `Terminal` and instead it was curiously on `Output`. Yesterday it happened again, was incessant for "a while" and then just stopped. Since I was thinking about the content of the code, I wasn't paying attention to what started/stopped it.

Today, I used GitLens to open a compare view of a past commit of a file, and `Output` panel popped and started spamming. 

I would post a video, but privacy. So to reproduce:

1. open a file in a project 
1. have GitLens installed
1. go to VSCode Source Control 
1. open File History panel
1. click original commit of the file
1. hover **_anything_** green in the file.

I know it initially sounds like it could be a GitLens problem, but I use this only because I know that it's a path for reliable reproduction. I don't use GitLens directly very often, but I happened to see it here and can give the steps to reproduce.

```
TypeError: must pass in a file:// URI to convert to a file path
    at Object.fileUriToPath (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/utils.js:25:15)
    at reloadDocument (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:69:70)
    at /home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:60:5
    at CallbackList.invoke (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at /home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-languageserver/lib/main.js:181:38
    at handleNotification (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate._onImmediate (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:461:21)
[Error - 9:53:21 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
[Error - 9:53:37 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
[Error - 9:53:37 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
[Error - 9:54:00 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
[Error - 9:54:02 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
```

The first `TypeError` scrolls up for 16.7km. Without timestamps I can't know how long they've been accumulating.

I have no problem helping directly as I can produce the problem reliably.

**Comment by theteladras** [comment]
The very mentioned issue seems to be present once again.

**Comment by HNazmul-X** [comment]
Me also Getting This Error. It's boring. it open my output terminal to many times.

**Comment by Meuss** [comment]
I'm also getting this error now, with a brand new sveltekit project.

I disabled this extension and enabled Svelte for VS Code instead, fixed my issue.

**Comment by ogrotten** [comment]
> I'm also getting this error now, with a brand new sveltekit project.
> 
> I disabled this extension and enabled Svelte for VS Code instead, fixed my issue.

Since this hasn't been touched in 3 yrs, that's probably for the best. At one point, this was the only game in town, but now there's an official extension.

**Comment by leetdavid** [comment]
This happens to me specifically when I open the version control diff page for a file and hover my mouse on the left side of that pane (the uneditable part).

```
[Error - 5:42:06 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
```

**Comment by gregg-cbs** [comment]
Oh my gosh thank you for this thread - i have removed this plugin. The terminal constantly popping up was extremely annoying and this is where I came to learn that you cannot ignore or hide this behavior.

I think the extension should disable the showing of terminal when an output is printed.

Also hopefully in a few days vscode will have a way to turn off this auto pop up behavior:
https://github.com/microsoft/vscode/pull/205225

**Comment by gjsjohnmurray** [comment]
> Also hopefully in a few days vscode will have a way to turn off this auto pop up behavior:
> [microsoft/vscode#205225](https://github.com/microsoft/vscode/pull/205225)

Now available in today's Insiders.
